### ISSUE TITLE
Connection Reset error

### ISSUE THREAD

**Issue by RyanPaulMcKenna** [Ice-mao/RL_AUV_tracking#2]
I run:

python SB3_learning.py --env TargetTracking1 --map TestMap_AUV --nb_envs 5 --choice 0 --render 0

and here is the console output and error:

```bash
test
test
test
test
test
test
Process ForkServerProcess-4:
Traceback (most recent call last):
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
AttributeError: module 'holoocean' has no attribute 'make'
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
AttributeError: module 'holoocean' has no attribute 'make'
Process ForkServerProcess-5:
Traceback (most recent call last):
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
AttributeError: module 'holoocean' has no attribute 'make'
Process ForkServerProcess-3:
Traceback (most recent call last):
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
AttributeError: module 'holoocean' has no attribute 'make'
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
AttributeError: module 'holoocean' has no attribute 'make'
Traceback (most recent call last):
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/SB3_learning.py", line 331, in <module>
    main()
  File "/home/ozwald/projects/ocean/RL_AUV_tracking/SB3_learning.py", line 124, in main
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 119, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/ozwald/anaconda3/envs/ocean/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Is it something to do with installing 'ocean' after installing holooean? As there seem to be multiple steps.

**Comment by Ice-mao** [comment]
I think the question is "AttributeError: module 'holoocean' has no attribute 'make'', the holoocean edtion i am using is 0.5.0, but now the edtion is not provided by the author.
The potential possibilities:
1、edtion 1.0.0 don't provide the holoocean.make() function;
2、the map can't load.You should build your own world in UE4.The scenario is just like a empty pool.
