### ISSUE TITLE
Could not find a package that contains world TestMap

### ISSUE THREAD

**Issue by mobi1019** [Ice-mao/RL_AUV_tracking#3]
hi, I move the two file : TestMap.json and TestMap_AUV.json to the path "/home/robot/.local/share/holoocean/1.0.0/worlds/Ocean",
then I run :`python3 SB3_learning.py --env TargetTracking1 --map TestMap_AUV --nb_envs 5 --choice 0 --render 0`
output is:
`test
test
test
test
test
test
Process ForkServerProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robot/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/robot/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/robot/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/robot/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/holoocean.py", line 79, in make
    package_config = get_package_config_for_scenario(scenario)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/packagemanager.py", line 447, in get_package_config_for_scenario
    raise HoloOceanException("Could not find a package that contains world {}".format(world_name))
holoocean.exceptions.HoloOceanException: Could not find a package that contains world TestMap
Process ForkServerProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robot/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/robot/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/robot/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/robot/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/holoocean.py", line 79, in make
    package_config = get_package_config_for_scenario(scenario)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/packagemanager.py", line 447, in get_package_config_for_scenario
    raise HoloOceanException("Could not find a package that contains world {}".format(world_name))
holoocean.exceptions.HoloOceanException: Could not find a package that contains world TestMap
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robot/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/robot/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/robot/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/robot/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/holoocean.py", line 79, in make
    package_config = get_package_config_for_scenario(scenario)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/packagemanager.py", line 447, in get_package_config_for_scenario
    raise HoloOceanException("Could not find a package that contains world {}".format(world_name))
holoocean.exceptions.HoloOceanException: Could not find a package that contains world TestMap
Process ForkServerProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robot/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/robot/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/robot/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/robot/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/holoocean.py", line 79, in make
    package_config = get_package_config_for_scenario(scenario)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/packagemanager.py", line 447, in get_package_config_for_scenario
    raise HoloOceanException("Could not find a package that contains world {}".format(world_name))
holoocean.exceptions.HoloOceanException: Could not find a package that contains world TestMap
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robot/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "SB3_learning.py", line 124, in <lambda>
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/robot/RL_AUV_tracking/auv_env/__init__.py", line 36, in make
    env0 = TargetTracking1(num_targets=num_targets, **kwargs)
  File "/home/robot/RL_AUV_tracking/auv_env/base.py", line 100, in __init__
    self.world = World_AUV(map=map, show=show, verbose=verbose, num_targets=self.num_targets)
  File "/home/robot/RL_AUV_tracking/auv_env/world_auv.py", line 27, in __init__
    self.ocean = holoocean.make(self.map)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/holoocean.py", line 79, in make
    package_config = get_package_config_for_scenario(scenario)
  File "/home/robot/.local/lib/python3.8/site-packages/holoocean/packagemanager.py", line 447, in get_package_config_for_scenario
    raise HoloOceanException("Could not find a package that contains world {}".format(world_name))
holoocean.exceptions.HoloOceanException: Could not find a package that contains world TestMap
Traceback (most recent call last):
  File "SB3_learning.py", line 331, in <module>
    main()
  File "SB3_learning.py", line 124, in main
    env = SubprocVecEnv([lambda: auv_env.make(args.env,
  File "/home/robot/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 119, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer`

I think there is something wrong with the path directory, can you show me how to config the json in detail? Thanks!

**Comment by Ice-mao** [comment]
The question occured is of env making,I update the readme.md and share my scenario.You can have a try again.If any question,issue again.

**Comment by overthink13** [comment]
hi, I move your scenario : TestMap.json and TestMap_AUV.json config.json  materials.csv to the path “/.local/share/holoocean/0.5.0/worlds” but still display this error.How to solve it?Thanks!
